.TH "TDR" "1" "" "tdr 1.3.1" "tdr"

.SH NAME
.B tdr - a text-based utility to manage todo list

.SH SYNOPSIS
\fBtdr\fR [\fIoptions\fR]

.SH DESCRIPTION
The \fBtdr\fR program manages your todo list. It allows user to create
different todo item with deadline time, and users can create multiple
workspaces for different todo list.

.SH OPTIONS

.HP
\fB-h, --help\fR
.br
Print usage information and exit.

.HP
\fB-v, --version\fR
.br
Print version information and exit.

.SH ITEM DISPLAY KEYBINDING

.HP
\fBk\fR
.br
Scroll up

.HP
\fBj\fR
.br
Scroll down

.HP
\fBw\fR
.br
Create new workspace

.HP
\fB-\fR
.br
Open workspace window

.HP
\fBa\fR
.br
Open add item window

.HP
\fBe\fR
.br
Open edit item window

.HP
\fBd\fR
.br
Delete selected item

.HP
\fBSpace\fR
.br
Toggle item's completion status

.HP
\fBx\fR
.br
Toggle item's completion status

.HP
\fBK\fR
.br
Scroll workspace up

.HP
\fBJ\fR
.br
Scroll workspace down

.HP
\fBr\fR
.br
Rename current workspace

.HP
\fBq, Ctrl-c\fR
.br
Quit program

.HP
\fB?\fR
.br
Toggle help window

.SH ADD ITEM KEYBINDING

.HP
\fBCtrl-d\fR
.br
Toggle input timestamp window

.HP
\fBEnter\fR
.br
Create item

.HP
\fBEscape\fR
.br
Exit add item window

.SH WORKSPACE DISPLAY KEYBINDING

.HP
\fBk\fR
.br
Scroll up

.HP
\fBj\fR
.br
Scroll down

.HP
\fBEnter\fR
.br
Enter selected workspace

.HP
\fBe\fR
.br
Edit name of selected workspace

.HP
\fBd\fR
.br
Delete selected workspace

.SH ADD WORKSPACE KEYBINDING

.HP
\fBEnter\fR
.br
Create workspace

.HP
\fBEscape\fR
.br
Exit add workspace window

.SH TIMESTAMP FORMAT

.HP
There are three different available timestamp formats which are:

.It
\fByear-month-date hour:minute:second\fR  [\fI####-##-## ##:##:##\fR]

.It
\fByear-month-date\fR  [\fI####-##-##\fR]

.It
\fBhour:minute:second\fR  [\fI##:##:##\fR]
