.TH "TODO-RS" "1" "" "tdr 1.3.1" "tdr"

.SH NAME
.B tdr

.SH SYNOPSIS
\fBtdr\fR [\fIoptions\fR]

.SH DESCRIPTION
\fBtdr\fR is a text-based user interface utility to manage todo list.

.SH OPTIONS

.HP
\fB-h, --help\fR
.br
Print usage information and exit.

.HP
\fB-v, --version\fR
.br
Print version information and exit.

.SH KEY BINDINGS

.HP
Item Display:

.It
<w>             Add workspace
.br
<->             Display workspace
.br
<a>             Add item
.br
<e>             Edit item
.br
<d>             Remove item
.br
<space>             Toggle item
.br
<r>             Rename current workspace
.br
<J>             Scroll workspace down
.br
<K>             Scroll workspace up
.br
<j>             Scroll down
.br
<k>             Scroll up
.br
<q>, <Ctrl-c>   Quit
.br
<?>             Toggle help display

.HP
Add Item:

.It
<Ctrl-d>        Toggle input timestamp
.br
<Enter>         Accept
.br
<Escape>        Exit

.HP
Workspace Display:

.It
<Enter>         Select workspace
.br
<e>             Edit workspace
.br
<d>             Delete workspace
.br
<j>             Scroll down
.br
<k>             Scroll up

.HP
Add Workspace:

.It
<Enter>         Accept
.br
<Escape>        Exit

.SH TIMESTAMP FORMAT

.HP
There are three different available timestamp formats which are:

.It
\fByear-month-date hour:minute:second\fR  [####-##-## ##:##:##]

.It
\fByear-month-date\fR  [####-##-##]

.It
\fBhour:minute:second\fR  [##:##:##]
